"""Build tables and figures exclusively from the verified 46 new training runs.

Adapted from the reviewed archived-inference plotting/statistics functions.
All inputs must be supplied by finish_revision_retraining.py; no old data is read.
"""
from __future__ import annotations
import argparse, csv, hashlib, itertools, json, math
from pathlib import Path
import numpy as np
import scipy
from scipy import stats
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

ROOT=DATA=FIG=None
TASKS=['temperature','humidity','component_of_wind','cloud_cover']
LABELS={'temperature':'Temperature','humidity':'Relative humidity','component_of_wind':'Surface wind','cloud_cover':'Cloud cover'}
UNITS={'temperature':'K','humidity':'percentage points','component_of_wind':'m s$^{-1}$','cloud_cover':'fraction'}
COLORS={'control':'#35658a','agf':'#c47a29'}
NAMES={'control':'Control','agf':'CLCRN-AGF'}
plt.rcParams.update({'font.family':'DejaVu Sans','font.size':8,'axes.titlesize':9,'axes.labelsize':8,'xtick.labelsize':7,'ytick.labelsize':7,'legend.fontsize':7,'axes.spines.top':False,'axes.spines.right':False,'pdf.fonttype':42,'ps.fonttype':42,'savefig.dpi':200})

def load(p): return json.loads(p.read_text(encoding='utf-8'))
def dump(p,o): p.write_text(json.dumps(o,indent=2,ensure_ascii=False),encoding='utf-8')
def csvout(name,rows):
    with (DATA/name).open('w',newline='',encoding='utf-8-sig') as f:
        w=csv.DictWriter(f,fieldnames=list(rows[0])); w.writeheader();w.writerows(rows)
def sha(p):
    h=hashlib.sha256()
    with p.open('rb') as f:
        for c in iter(lambda:f.read(8*1024*1024),b''):h.update(c)
    return h.hexdigest()
def save(fig,name):
    FIG.mkdir(parents=True,exist_ok=True)
    for suffix in ['pdf','png']: fig.savefig(FIG/f'{name}.{suffix}',bbox_inches='tight')
    plt.close(fig)
def bh(p):
    order=np.argsort(p); result=np.empty(len(p)); adjusted=np.minimum.accumulate((np.array(p)[order]*len(p)/np.arange(1,len(p)+1))[::-1])[::-1];result[order]=np.minimum(adjusted,1);return result
def exactperm(a,b):
    both=np.r_[a,b];obs=abs(a.mean()-b.mean());diff=[]
    for inds in itertools.combinations(range(10),5):
        x=both[list(inds)]; diff.append(abs(x.mean()-(both.sum()-x.sum())/5))
    return np.mean(np.array(diff)>=obs-1e-12)
def compare(a,b):
    # a is AGF, b is control. Welch is unpaired by design.
    va=a.var(ddof=1);vb=b.var(ddof=1);se=np.sqrt(va/len(a)+vb/len(b));df=(va/len(a)+vb/len(b))**2/((va/len(a))**2/(len(a)-1)+(vb/len(b))**2/(len(b)-1));delta=a.mean()-b.mean();width=stats.t.ppf(.975,df)*se
    return {'control_mean':b.mean(),'control_sd':b.std(ddof=1),'agf_mean':a.mean(),'agf_sd':a.std(ddof=1),'difference':delta,'ci95_low':delta-width,'ci95_high':delta+width,'welch_df':df,'welch_p':stats.ttest_ind(a,b,equal_var=False).pvalue,'exact_permutation_p':exactperm(a,b),'relative_change_percent':delta/b.mean()*100}

def main():
    rows=[r for p in sorted(DATA.glob('inference_*.json')) if 'kind' in (r:=load(p))]
    primary=[r for r in rows if r['kind'] in ['agf','control']]
    assert len(primary)==40, f'Expected 40 complete primary runs, found {len(primary)}'
    assert len({(r['kind'],r['dataset'],r['seed']) for r in primary})==40
    index={(r['kind'],r['dataset'],r['seed']):r for r in primary}
    def vals(kind,task,metric,seeds=range(2021,2026)): return np.array([index[kind,task,s]['metrics'][metric] for s in seeds])
    statrows=[]
    for task in TASKS:
        for metric in ['mae','rmse']:
            statrows.append({'dataset':task,'metric':metric,'n_control':5,'n_agf':5,**compare(vals('agf',task,metric),vals('control',task,metric))})
    for key in ['welch','exact_permutation']:
        for r,q in zip(statrows,bh([r[f'{key}_p'] for r in statrows])): r[f'{key}_bh_q']=q
    csvout('table1_primary_statistics.csv',statrows)
    csvout('primary_per_seed.csv',[{'kind':r['kind'],'dataset':r['dataset'],'seed':r['seed'],'epoch':r['corrected_best_epoch'],'mae':r['metrics']['mae'],'rmse':r['metrics']['rmse'],'latitude_weighted_mae':r['metrics']['weighted_mae'],'latitude_weighted_rmse':r['metrics']['weighted_rmse'],'checkpoint':r['checkpoint']['path'],'checkpoint_sha256':r['checkpoint']['sha256']} for r in primary])
    weighted=[]
    for task in TASKS:
        for metric in ['weighted_mae','weighted_rmse']:
            weighted.append({'dataset':task,'metric':metric,**compare(vals('agf',task,metric),vals('control',task,metric))})
    for r,q in zip(weighted,bh([r['welch_p'] for r in weighted])):r['welch_bh_q']=q
    csvout('latitude_weighted_sensitivity.csv',weighted)
    out=['% Generated by data_build_artifacts.py; table body for tab:primary']
    for r in statrows:
        d=4 if r['dataset']=='cloud_cover' else 3
        out.append(f"{LABELS[r['dataset']]} & {r['metric'].upper()} & ${r['control_mean']:.{d}f}\\pm{r['control_sd']:.{d}f}$ & ${r['agf_mean']:.{d}f}\\pm{r['agf_sd']:.{d}f}$ & ${r['difference']:+.{d}f}$ [${r['ci95_low']:+.{d}f},{r['ci95_high']:+.{d}f}$] & {r['welch_p']:.4g} \\\\")
    (DATA/'table1_body.tex').write_text('\n'.join(out)+'\n',encoding='utf-8')
    context=[]
    for task in TASKS:
        for name in ['Persistence','Control','CLCRN-AGF']:
            if name=='Persistence':met=load(DATA/f'persistence_{task}.json');n=1
            elif name=='Reproduced CLCRN':
                rr=[r for r in rows if r['kind']=='original' and r['dataset']==task]
                if not rr:continue
                met=rr[0]['metrics'];n=1
            else:
                kind='control' if name=='Control' else 'agf';met={m:vals(kind,task,m).mean() for m in ['mae','rmse']};n=5
            context.append({'dataset':task,'method':name,'n_seed':n,'mae':met['mae'],'rmse':met['rmse'],'metric_definition':'zero-inclusive, spatially unweighted, cumulative t+1:t+12'})
    csvout('table2_current_context.csv',context)
    lines=['% Same split/evaluator; no externally sourced numbers in this table.']
    for name in ['Persistence','Control','CLCRN-AGF']:
        rr=[r for t in TASKS for r in context if r['dataset']==t and r['method']==name]
        if len(rr)==4:
            v=[f"{r[m]:.{4 if r['dataset']=='cloud_cover' else 3}f}" for r in rr for m in ['mae','rmse']]
            lines.append(name+' & '+' & '.join(v)+' \\\\')
    (DATA/'table2_body.tex').write_text('\n'.join(lines)+'\n',encoding='utf-8')
    # Ablation full/control deliberately reuse the identical three main runs.
    ablations=[]; ablation_seeds=[]
    for task in ['temperature','humidity']:
        for kind,name in [('control','w/o adaptive graph'),('mean_fusion','Mean fusion'),('agf','Full CLCRN-AGF')]:
            rr=[r for r in rows if r['kind']==kind and r['dataset']==task and r['seed'] in [2023,2024,2025]]
            if len(rr)!=3:continue
            entry={'dataset':task,'variant':name,'n_seeds':3,'seeds':'2023;2024;2025','training_precision':'FP32'}
            for m in ['mae','rmse']:
                v=np.array([r['metrics'][m] for r in rr]);entry[m+'_mean']=v.mean();entry[m+'_sd']=v.std(ddof=1)
            ablations.append(entry)
            ablation_seeds.extend({'dataset':task,'variant':name,'seed':r['seed'],'checkpoint':r['checkpoint']['path'],'checkpoint_sha256':r['checkpoint']['sha256'],'mae':r['metrics']['mae'],'rmse':r['metrics']['rmse']} for r in rr)
    if ablations:
        csvout('table3_ablation_statistics.csv',ablations);csvout('ablation_per_seed.csv',ablation_seeds)
        (DATA/'table3_body.tex').write_text('\n'.join(f"{LABELS[r['dataset']]} & {r['variant']} & {r['training_precision']} & ${r['mae_mean']:.3f}\\pm{r['mae_sd']:.3f}$ & ${r['rmse_mean']:.3f}\\pm{r['rmse_sd']:.3f}$ \\\\" for r in ablations)+'\n',encoding='utf-8')
    horizon=[]
    for r in primary:
        for h in range(12):
            horizon.append({'kind':r['kind'],'dataset':r['dataset'],'seed':r['seed'],'lead_hours':h+1,**{m:r['metrics'][m][h] for m in ['exact_mae','exact_rmse','cumulative_mae','cumulative_rmse']}})
    csvout('horizon_per_seed.csv',horizon)
    # Fig 3: all local contextual rows now regenerated from current split.
    fig,axes=plt.subplots(1,4,figsize=(7.2,2.15))
    methods=['Persistence','Control','CLCRN-AGF']
    for ax,task,letter in zip(axes,TASKS,'abcd'):
        rr=[next((r for r in context if r['dataset']==task and r['method']==m),None) for m in methods]
        if any(r is None for r in rr):continue
        ax.bar(range(3),[r['mae'] for r in rr],color=['#aeb6be',COLORS['control'],COLORS['agf']])
        ax.set_xticks(range(3),['Persist.','Control','AGF'],rotation=35,ha='right');ax.set_ylabel('MAE ('+UNITS[task]+')');ax.set_title(letter+'  '+LABELS[task]);ax.grid(axis='y',alpha=.2);ax.set_axisbelow(True)
    fig.tight_layout(w_pad=1.3);save(fig,'fig3_context_current_split')
    # Fig 4: actual seed-level uncertainty, separate units and metric panels.
    fig,axes=plt.subplots(2,4,figsize=(7.2,3.7))
    for j,task in enumerate(TASKS):
        for i,m in enumerate(['mae','rmse']):
            ax=axes[i,j]
            for k,kind in enumerate(['control','agf']):
                v=vals(kind,task,m);ax.scatter(k+np.linspace(-.1,.1,5),v,s=14,color=COLORS[kind],zorder=3);ax.errorbar(k,v.mean(),yerr=v.std(ddof=1),fmt='D',color='#252525',markersize=3,capsize=3,lw=.8,zorder=4)
            ax.set_xticks([0,1],['Control','AGF']);ax.set_ylabel(m.upper()+' ('+UNITS[task]+')');ax.set_xlim(-.4,1.4);ax.grid(axis='y',alpha=.2)
            if i==0:ax.set_title(LABELS[task])
    fig.tight_layout(w_pad=1.3);save(fig,'fig4_primary_replicates')
    # Fig 5: exact and cumulative means from the very same 40 checkpoints.
    fig,axes=plt.subplots(2,2,figsize=(7.2,4.5),sharex=True)
    for ax,task in zip(axes.ravel(),TASKS):
        for kind in ['control','agf']:
            for key,ls,desc in [('exact_mae','-','exact'),('cumulative_mae','--','cumulative')]:
                v=np.array([index[kind,task,s]['metrics'][key] for s in range(2021,2026)])
                ax.plot(range(1,13),v.mean(0),ls,color=COLORS[kind],label=NAMES[kind]+' '+desc,lw=1.4)
                if key=='exact_mae':ax.fill_between(range(1,13),v.mean(0)-v.std(0,ddof=1),v.mean(0)+v.std(0,ddof=1),color=COLORS[kind],alpha=.13)
        ax.set_title(LABELS[task]);ax.set_ylabel('MAE ('+UNITS[task]+')');ax.set_xlabel('Lead time (hours)');ax.set_xticks([1,3,6,9,12]);ax.grid(alpha=.2)
    fig.legend(*axes[0,0].get_legend_handles_labels(),loc='upper center',ncol=2,bbox_to_anchor=(.5,1.02),frameon=False);fig.tight_layout(rect=[0,0,1,.93]);save(fig,'fig5_horizon_consistent')
    # Fig 6: primary comparisons only; no unsupported causal schedule attribution.
    fig,axes=plt.subplots(1,2,figsize=(7.2,2.6),sharey=True)
    for ax,m in zip(axes,['mae','rmse']):
        for i,task in enumerate(TASKS):
            r=next(r for r in statrows if r['dataset']==task and r['metric']==m);factor=100/r['control_mean'];d=r['difference']*factor;lo=r['ci95_low']*factor;hi=r['ci95_high']*factor
            ax.errorbar(d,3-i,xerr=[[d-lo],[hi-d]],fmt='o',color=COLORS['agf'],capsize=3,markersize=4);ax.text(d,3-i+.15,f'{d:+.2f}%',ha='center',fontsize=7)
        ax.axvline(0,color='#555',ls=':',lw=1);ax.set_yticks(range(4),[LABELS[t] for t in TASKS[::-1]]);ax.set_title(m.upper());ax.set_xlabel('AGF − control (% of control mean)');ax.grid(axis='x',alpha=.2);ax.set_ylim(-.5,3.5)
    fig.tight_layout();save(fig,'fig6_primary_effects')
    # Fig 7: first average mask replicates within a trained seed, then SD across seeds.
    robust=[];rsummary=[]
    fig,axes=plt.subplots(2,2,figsize=(7.2,4.3),sharex=True)
    for ax,task in zip(axes.ravel(),TASKS):
        for kind in ['control','agf']:
            seedcurves=[]
            for s in range(2021,2026):
                rr=index[kind,task,s]['robustness'];base=next(r['mae'] for r in rr if r['ratio']==0);curve=[]
                for ratio in [0,.1,.2,.3,.4]:
                    subset=[r for r in rr if r['ratio']==ratio];mean=np.mean([r['mae'] for r in subset]);change=(mean/base-1)*100;curve.append(change)
                    for r in subset:robust.append({'kind':kind,'dataset':task,'seed':s,**r,'clean_mae_same_subset':base,'relative_increase_percent':(r['mae']/base-1)*100})
                seedcurves.append(curve)
            arr=np.array(seedcurves);mean=arr.mean(0);sd=arr.std(0,ddof=1)
            ax.errorbar([0,10,20,30,40],mean,yerr=sd,marker='o' if kind=='control' else 's',markersize=3,capsize=2,color=COLORS[kind],lw=1.2,label=NAMES[kind])
            rsummary.extend({'kind':kind,'dataset':task,'missing_ratio':ratio,'mean_relative_mae_increase_percent':mean[i],'sd_across_trained_seeds_percent':sd[i],'n_trained_seeds':5,'n_masks_per_nonzero_ratio':3,'test_examples':64} for i,ratio in enumerate([0,.1,.2,.3,.4]))
        ax.set_title(LABELS[task]);ax.set_xlabel('Masked nodes (%)');ax.set_ylabel('MAE increase vs clean (%)');ax.grid(alpha=.2)
    fig.legend(*axes[0,0].get_legend_handles_labels(),loc='upper center',ncol=2,bbox_to_anchor=(.5,1.02),frameon=False);fig.tight_layout(rect=[0,0,1,.96]);save(fig,'fig7_robustness_consistent');csvout('robustness_per_seed_mask.csv',robust);csvout('robustness_summary.csv',rsummary)
    # Fig 8: actual scalar gates, not an unexplained channel-averaged proxy.
    grows=[];gateper=[];ghist=[]
    fig,axes=plt.subplots(1,4,figsize=(7.2,2.05),sharex=True)
    for ax,task in zip(axes,TASKS):
        rr=[index['agf',task,s]['gates'] for s in range(2021,2026)];n=sum(r['n_scalar_gates'] for r in rr);mean=sum(r['mean']*r['n_scalar_gates'] for r in rr)/n;second=sum((r['population_std']**2+r['mean']**2)*r['n_scalar_gates'] for r in rr)/n;sd=np.sqrt(max(0,second-mean**2));hist=np.sum([r['histogram_counts'] for r in rr],axis=0);edges=np.array(rr[0]['histogram_edges']);centers=(edges[:-1]+edges[1:])/2
        grows.append({'dataset':task,'mean':mean,'pooled_population_std':sd,'min':min(r['min'] for r in rr),'max':max(r['max'] for r in rr),'n_scalar_gates':n,'n_seeds':5,'n_test_examples_per_seed':rr[0]['n_test_examples'],'gate_channels':rr[0]['gate_channels'],'input_steps':rr[0]['input_steps']})
        for seed,g in zip(range(2021,2026),rr):
            ax.plot(centers,np.array(g['histogram_counts'])/g['n_scalar_gates']/.01,color='#aeb6be',lw=.6,alpha=.75)
            gateper.append({'dataset':task,'seed':seed,**{k:v for k,v in g.items() if k not in ['histogram_counts','histogram_edges','grain']}})
            ghist.extend({'dataset':task,'seed':seed,'bin_left':edges[i],'bin_right':edges[i+1],'count':count} for i,count in enumerate(g['histogram_counts']))
        ax.plot(centers,hist/n/.01,color=COLORS['agf'],lw=1.6);ax.axvline(.5,color='#555',ls=':',lw=.8);ax.set_title(LABELS[task]);ax.set_xlabel('Scalar gate g');ax.set_xlim(0,1);ax.set_ylabel('Density');ax.grid(axis='y',alpha=.2)
    fig.tight_layout(w_pad=1);save(fig,'fig8_gate_consistent');csvout('table4_gate_statistics.csv',grows);csvout('gate_per_seed.csv',gateper);csvout('gate_histogram.csv',ghist)
    (DATA/'table4_body.tex').write_text('\n'.join(f"{LABELS[r['dataset']]} & {r['mean']:.3f} & {r['pooled_population_std']:.3f} & {r['min']:.3f} & {r['max']:.3f} \\\\" for r in grows)+'\n',encoding='utf-8')
    zero=[]
    for task in TASKS:
        ds=load(DATA/f'dataset_{task}.json')
        for split,st in ds.get('raw_target_zeros',{}).items():zero.append({'dataset':task,'split':split,**st})
    if zero:csvout('raw_target_zero_fractions.csv',zero)
    figures={
      'fig3_context_current_split.pdf':{'original_figure':3,'data':'table2_current_context.csv','caption':'Current-split cumulative 12-hour MAE. Persistence is deterministic; control and AGF are five-seed means. All results use the same zero-inclusive, spatially unweighted evaluator. Panels have task-specific physical units. This is contextual, not a causal decomposition of schedule changes.'},
      'fig4_primary_replicates.pdf':{'original_figure':4,'data':'primary_per_seed.csv','caption':'Cumulative 12-hour MAE (top) and RMSE (bottom) from the same 40 checkpoints used in Table 1. Coloured points are five independently trained replicates per variant; black diamonds/error bars denote mean plus or minus sample standard deviation. No pairing of seed labels is assumed.'},
      'fig5_horizon_consistent.pdf':{'original_figure':5,'data':'horizon_per_seed.csv','caption':'Exact-lead MAE (solid) and cumulative MAE from lead 1 to each plotted hour (dashed), averaged over the same five seeds per variant as Table 1. Shading denotes plus or minus sample SD across seeds for exact-lead MAE. Cumulative endpoints at 12 hours equal the corresponding Table 1 MAEs; panels use task-specific units.'},
      'fig6_primary_effects.pdf':{'original_figure':6,'data':'table1_primary_statistics.csv','caption':'AGF-minus-control mean differences and 95% Welch intervals from Table 1, divided by the corresponding observed control mean and expressed as percentages. Negative values favour AGF. These are rescaled difference intervals, not confidence intervals from a separate ratio estimator. No single selected AGF run or historical schedule result enters this figure.'},
      'fig7_robustness_consistent.pdf':{'original_figure':7,'data':'robustness_per_seed_mask.csv','caption':'Exploratory missing-input stress test using 64 deterministically spaced test windows, the same five trained seeds per variant as Table 1, and three mask seeds (11, 22, 33) at each nonzero ratio. A node mask is fixed across 12 input hours and all signal channels; standardized inputs are set to zero (training-mean imputation). Changes are relative to the clean score on the same 64 windows for each checkpoint. Masks are averaged within a trained seed; points/error bars show mean plus or minus sample SD across five trained seeds. These are sampled diagnostics, not complete-test performance or statistical significance tests.'},
      'fig8_gate_consistent.pdf':{'original_figure':8,'data':'gate_histogram.csv','caption':'Full-test distributions of scalar sigmoid gates for all four tasks and the same five AGF checkpoints as Table 1. Gates are collected over 657 test windows, 12 input hours, 2048 nodes and 8 output channels per seed. Thin grey curves are individual seeds and the coloured curve is the pooled 100-bin density. The gate mixes adaptive graph aggregation and a nodewise residual projection before CLConv. Gate magnitudes do not by themselves measure the relative contribution of the two branches.'}}
    dump(DATA/'manuscript_assets.json',{'figures':figures,'tables':{'primary':'table1_body.tex','context':'table2_body.tex','ablation':'table3_body.tex','gate':'table4_body.tex'},'statistics':statrows,'weighted_sensitivity':weighted,'gate_statistics':grows,'ablation_statistics':ablations,'max_abs_new_training_metric_difference':max(abs(v) for r in primary for v in r['new_training_metric_differences'].values()),'training':{'all_runs_new':True,'primary_runs':40,'mean_fusion_runs':6,'epochs_per_run':100,'precision':'FP32','loss_protocol':'zero_inclusive','validation_protocol':'zero_inclusive'},'software':{'numpy':np.__version__,'scipy':scipy.__version__,'matplotlib':matplotlib.__version__}})
    print('Created new-training statistics and figures for 40 primary + 6 ablation runs.',flush=True)


def build(run_root, data_dir, figure_dir):
    global ROOT,DATA,FIG
    ROOT=Path(run_root).resolve();DATA=Path(data_dir).resolve();FIG=Path(figure_dir).resolve()
    rows=[load(p) for p in sorted(DATA.glob('inference_*.json'))]
    expected={(t,v,s) for t in TASKS for v in ['control','agf'] for s in range(2021,2026)} | {(t,'mean_fusion',s) for t in ['temperature','humidity'] for s in [2023,2024,2025]}
    assert len(rows)==46 and {(r['dataset'],r['kind'],r['seed']) for r in rows}==expected
    assert all(r['training_performed'] and r['training_protocol']=='zero_inclusive' and r['training_precision']=='FP32' and r['epochs_completed']==100 for r in rows)
    for r in rows:
        m=r['metrics']
        assert abs(m['cumulative_mae'][-1]-m['mae'])<1e-12
        assert abs(m['cumulative_rmse'][-1]-m['rmse'])<1e-12
        if r['kind'] in ['agf','control']:
            assert len(r['robustness'])==13
            assert all(x['n_examples']==64 for x in r['robustness'])
        if r['kind']=='agf':
            g=r['gates'];assert g['n_scalar_gates']==g['n_test_examples']*g['input_steps']*g['nodes']*g['gate_channels']
    main()
    assets=load(DATA/'manuscript_assets.json')
    assets['manuscript_updated']=False
    assets['evidence_source']='46 newly trained runs only; no historical inference mixed in'
    dump(DATA/'manuscript_assets.json',assets)
    lines=['New training analysis completed: 40 primary runs and 6 mean-fusion ablations.',
           'All runs completed 100 epochs with FP32 and zero-inclusive training and validation.',
           'The checkpoint is selected solely by minimum full validation MAE.',
           'Primary statistics: five independent runs per variant; Welch comparison, exact permutation sensitivity and BH adjustment.',
           'Ablations: temperature and humidity, three seeds each; main-run control/AGF checkpoints are reused.',
           'Robustness: diagnostic subset of 64 test windows, three mask seeds; not full-test performance.',
           'Manuscript has NOT been updated. Interpret these new results before revising claims.', '']
    for r in assets['statistics']:
        lines.append(f"{r['dataset']} {r['metric']}: control {r['control_mean']:.6g} +/- {r['control_sd']:.4g}; AGF {r['agf_mean']:.6g} +/- {r['agf_sd']:.4g}; relative change {r['relative_change_percent']:+.3f}%; Welch p={r['welch_p']:.6g}, BH q={r['welch_bh_q']:.6g}.")
    (DATA.parent/'RESULTS_README.txt').write_text('\n'.join(lines)+'\n',encoding='utf-8')


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--run-root',type=Path,required=True)
    parser.add_argument('--data-dir',type=Path,required=True)
    parser.add_argument('--figure-dir',type=Path,required=True)
    args=parser.parse_args()
    build(args.run_root,args.data_dir,args.figure_dir)
